services:
  - type: web
    name: spx-gc
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: RENDER
        value: true
    healthCheckPath: /
    autoDeploy: true
    plan: free
    region: oregon
    disk:
      name: spx-data
      mountPath: /opt/render/project/src/DATAROOT
      sizeGB: 1 